# Generated by Django 2.2.3 on 2019-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190711_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
