# Generated by Django 2.2.3 on 2019-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
